### ISSUE TITLE
Option to query for hidden channels

### ISSUE THREAD

**Issue by hammadj** [smilefam/SendBird-SDK-JavaScript#71]
Right now, as far as I can tell, there is no way to search/access hidden channels on the client. It would be great to have an `includeHidden` option in GroupChannelListQuery.

**Comment by doertli** [comment]
This is a required feature - otherwise there no way for a user to navigate to hidden conversations. Both WhatsApp and FB Messenger allow “archived” (their name for “hidden”) conversations to be discovered via search.

**Comment by Alchemist85K** [comment]
@hammadj @doertli 
Thank you for your interest in SendBird SDK.
Thank you for your good feedback.
we'll share and discuss it with the team.

**Comment by Alchemist85K** [comment]
@doertli 
I'm sorry I did not say anything.
There are currently no plan to add this option.
However, I shared the problem with team and they are aware of it.
Thank you for your feedback.

**Comment by doertli** [comment]
@Alchemist85K that's really not an acceptable answer. When a user hides/archives a chat (various apps call it either 'hide', like iMessage, or 'archive', like Whatsapp), there simply NEEDS to be a way for the user to get back to it.

It's literally a broken UX otherwise and we have no workarounds for the user to rediscover hidden/archived chats without this method.

**Further, this is a super simply thing for Sendbird to fix**. Just make a 'showhidden' param available in your existing methods for displaying conversations.

**Comment by gianpaj** [comment]
I believe this should be easy to implement without waiting for the SDK to have this built-in.

Create a channel with some metadata like this (if 1-to-1 chat):
```js
{
  isVisibleA: true,
  isVisibleB: true,
}
```
Then change the visible parameter for the user who hides/unhides the chat (via the UI).

To hide the chat from the channel list, check the metadata before showing.

**Comment by doertli** [comment]
Agree, but at that point we’re forking Sendbird “hide” and using our own hacked “hide” feature, just so the discovery part of the “hide” feature can work.

The better path is for Sendbird to just do the final little piece of work to get hide working properly.

**Comment by doertli** [comment]
Note also there’s more complexity required to hack around Sendbird. For instance, when a new message is sent to a hidden conversation, Sendbird automatically unhides for all participants (this is correct).

But then our own hide meta data is wrong, because it only takes into account discrete hide/unhide. Unless we do another hack to check Sendbird new messages, and manually reset this meta data... but then the hack arounds get deeper again and more fragile.

**Comment by doertli** [comment]
Good stuff! Look forward to testing it before end April. Thank you!

**Comment by frankyjuang** [comment]
Any updates on this? Still can't find any document about this. Is it implemented?
