### ISSUE TITLE
React Native: Push Notification Issue (Android)

### ISSUE THREAD

**Issue by Dimasik911** [smilefam/SendBird-SDK-JavaScript#95]
Sendbord SDK v: "3.0.88"

Hello, I encounter an issue with sb Push notifications on Android devices (IOS works fine). I am using "react-native-firebase" as Firebase lib. In SB dashboard I see right GCM push token and able to send Push Notifications through Firebase console and it is just works fine (that probably means that I'm passing the right token), but in case when app is in bg mode and when somebody sends a message it doesn't work. What could be an issue here?

P.S. I'm also using `sb.setForegroundState` and `sb.setBackgroundState` functions.

**Comment by chrisallo** [comment]
I am not sure you just did everything what `react-native-firebase` docs says, but I'd like to give you a checklist so that you can make it work.

- register push token by calling `sb.unregisterGCMPushTokenForCurrentUser()` whenever the token is refreshed.
- add `<service android:name="io.invertase.firebase.messaging.RNFirebaseBackgroundMessagingService" />` into application tag in AndroidManifest.xml
- add background push handler as [this document](https://rnfirebase.io/docs/v5.x.x/messaging/receiving-messages#4\)-\(Optional\)\(Android-only\)-Listen-for-FCM-messages-in-the-background) guides.
- for displaying local notification, make sure that you provided default channel ID and notification icon in AndroidManifest.xml in case of Android Oreo+.
